name: jayesseff
favicon: null
layout_spectrum: 0.74715
typography_spectrum: 0.34925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1415'
    - '#88a890'
    - '#5e6b40'
    - '#fbdbc6'
    - '#b18264'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
