name: jayesseff
favicon: null
layout_spectrum: 0.9544505849480629
typography_spectrum: 0.6346602593548596
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0
  lightness: 0.736909726401791
  saturation: 0.6269290097989142
  rhythmicContrast: 0.9622764112427831
purpose: []
